name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches: 
        - "main"
  pull_request:
    branches: 
        - "main"

# permissions:
#   contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    # Step1: Checkout the code from the repository
    - name: Check out code
      uses: actions/checkout@v2

    # Step2: Setup python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    # Step3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.
        
    # Step4: Run tests
    - name: Run tests
      run: pytest
